# Generated by Django 2.2.13 on 2021-04-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='hora',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
    ]
