# Generated by Django 2.2.13 on 2021-04-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210422_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignation',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
    ]
