# Generated by Django 2.2.13 on 2021-04-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_asignation_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignation',
            name='asignation_student',
            field=models.ManyToManyField(through='api.AsignationStudent', to='api.Student'),
        ),
    ]
