# Generated by Django 2.2.13 on 2021-04-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210424_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.FileField(blank=True, null=True, upload_to='tareas')),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.CharField(max_length=6)),
                ('note', models.DecimalField(decimal_places=2, max_digits=3)),
                ('asignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Asignation')),
            ],
            options={
                'verbose_name': 'Model base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('field', models.FileField(blank=True, null=True, upload_to='tareas/estudiantes')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name': 'Model base',
                'abstract': False,
            },
        ),
    ]
