# Generated by Django 2.2.13 on 2021-04-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210429_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmaterial',
            options={},
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
