# Generated by Django 2.2.13 on 2021-04-29 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210429_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmaterial',
            name='asignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignations', to='api.Asignation'),
        ),
    ]
