# Generated by Django 2.2.13 on 2021-04-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210429_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmaterial',
            old_name='directory_file',
            new_name='directory_field',
        ),
    ]
