# Generated by Django 2.2.13 on 2021-04-29 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210429_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
        migrations.AlterField(
            model_name='homework',
            name='asignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignations_homework', to='api.Asignation'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='delivery_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
