# Generated by Django 2.2.13 on 2021-05-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210501_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='note',
            field=models.IntegerField(),
        ),
    ]
