# Generated by Django 2.2.13 on 2021-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210504_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstudent',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
