# Generated by Django 2.2.13 on 2021-05-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210505_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignationstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignation_students', to='api.Student'),
        ),
    ]
